### ISSUE TITLE
Scrolling/zoom on cursor position

### ISSUE THREAD

**Issue by ghost** [renatopp/behavior3editor#17]
One thing that is really preventing me from using the editor right now is the impossibility to "scroll" the page to left/right and top/down.

Zooming only zooms the center of the graph and, unless I'm missing something obvious, it's impossible to work on the edges of the project with a decent level of zoom.

**Comment by renatopp** [comment]
Hi, @happyemi, thanks for the feedback.

Actually, you can drag the screen using the mouse middle button (click and drag). However, this isn't good for notebooks, so I will add arrows to do the same things.

About the zoom, this is really annoying and I hope to fix that soon. Next week I will start a new development iteration on b3editor.

**Comment by renatopp** [comment]
@happyemi The zoom is still on the (0, 0), but now you can move the camera with the arrows.

You can check out the next version in:
http://behavior3js.guineashots.com/editor/dev

**Comment by ghost** [comment]
It's great! Very happy to see this project making progress.
